# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-05 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import routeoptimizer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('key_expiration', models.DateTimeField(default=routeoptimizer.models._generate_expiration)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(default='arret_stm', max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_people', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routeoptimizer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=99, null=True)),
                ('global_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='routeoptimizer.GlobalVar')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('start_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('current_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.AddField(
            model_name='stop',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routeoptimizer.Tour'),
        ),
    ]
